config/routes.rb
Rails.application.routes.draw do
  get 'purchase/index'
  get 'purchase/done'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  root to: 'items#index'

  resources :users, only: [:index]
  resources :mypages, only: [:show, :index]
  resources :creditcards

  
  resources :products do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'purchase_check', to:'products#purchase_check'
      post 'purchase_completed', to:'products#purchase_completed'
      get 'done', to: 'products#done'
      get 'products/:id' => 'products#show'
      get 'purchase_completed'
    end
  end

  resources :addresses , only: [:new, :create ]

  # 削除済商品へのアクセスした場合のエラー画面を表示するためのルーティング
  get 'not_found', to:'products#not_found'

  # クレジットカード登録ページのルーティング
  get 'card', to:'mypages#card'

  end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user, optional: true
  validates :prefecture, :city, :house_number, presence: true
  validates :postnumber, presence: true,
  format: {
    with: /\A\d{3}[-]\d{4}\z/,
    message: "はハイフン(-)付き半角７桁で入力して下さい"
  }
  validates :first_name, :last_name, presence: true,
  format: {
    with: /\A[ぁ-んァ-ン一-龥]/,
    message: "は全角（ひらがな、カタカナ、漢字）のみで入力して下さい"
  }
  validates :first_name_kana, :last_name_kana, presence: true,
  format: {
    with: /\A[ァ-ヶー－]+\z/,
    message: "は全角カタカナのみで入力して下さい"
  }

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_ancestry
  has_many :products
end

app/models/creditcard.rb
class Creditcard < ApplicationRecord
  belongs_to :user

  validates :card_id, presence: true
  validates :user_id, presence: true
  validates :customer_id, presence: true

end

app/models/delivery_fee.rb
class DeliveryFee < ActiveHash::Base
  self.data = [
    {id: 1, name: '送料込み（出品者負担）'}, {id: 2, name: '着払い（購入者負担）'}
  ]
end

app/models/delivery_time.rb
class DeliveryTime < ActiveHash::Base
  self.data = [
    {id: 1, name: '1~2日で発送'}, {id:2, name: '2~3日で発送'},
    {id: 3, name: '4~7日で発送'}
  ]
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :product, optional: true
  mount_uploader :image, ImageUploader
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :images, dependent: :destroy
  belongs_to :category

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :size 
  belongs_to_active_hash :product_status 
  belongs_to_active_hash :delivery_fee 
  belongs_to_active_hash :delivery_time

  accepts_nested_attributes_for :images, allow_destroy: true
  validates_associated :images
  validates :images, presence: { message:"は1つ以上登録してください" }
  validates :product_name, length: { maximum: 40 }, presence: true
  validates :product_detail, presence: true
  validates :category_id, :size_id, :product_status_id, :delivery_area, :delivery_fee_id, :delivery_time_id, presence: { message: "を選択してください"}
  
  validates :price, inclusion: {in: 300..9999999, message: "は300~9,999,999の範囲で入力してください" }, presence: true

end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/product_status.rb
class ProductStatus < ActiveHash::Base
  self.data = [
    {id: 1, name: '新品、未使用'}, {id:2, name: '未使用に近い'},
    {id: 3, name: '目立った傷や汚れなし'}, {id:4, name: 'やや傷や汚れあり'},
    {id: 5, name: '傷や汚れあり'}, {id:6, name: '全体的に状態が悪い'}
  ]
end

app/models/size.rb
class Size < ActiveHash::Base
  self.data = [
    {id: 1, name: 'XXS以下'}, {id: 2, name: 'XS(SS)'},
    {id: 3, name: 'S'}, {id: 4, name: 'M'},
    {id: 5, name: 'L'}, {id: 6, name: 'XL(LL)'},
    {id: 7, name: '2XL(3L)'}, {id: 8, name: '3XL(4L)'},
    {id: 9, name: '4XL(5L)以上'}, {id: 10, name: 'FREE SIZE'}
  ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, :birthday, presence: true
  validates :first_name, :last_name, presence: true,
    format: {
      with: /\A[ぁ-んァ-ン一-龥]/,
      message: "は全角（ひらがな、カタカナ、漢字）のみで入力して下さい"
    }
  validates :first_name_kana, :last_name_kana, presence: true,
    format: {
      with: /\A[ァ-ヶー－]+\z/,
      message: "は全角カタカナのみで入力して下さい"
    }

    has_one :address
    has_many :products
    has_many :creditcards
end

app/controllers/creditcards_controller.rb
class CreditcardsController < ApplicationController
  require 'payjp'

  def index
  end

  def new
    if current_user.creditcards.present?
      redirect_to creditcard_path(current_user.creditcards[0].id)
    end
    creditcard = Creditcard.where(user_id: current_user.id)
  end

  def create
    Payjp.api_key = ENV['PAYJP_ACCESS_KEY']
    if params["payjp_token"].blank?
      redirect_to action: "new", alert: "クレジットカードを登録できませんでした"
    else
      customer = Payjp::Customer.create(
        card: params["payjp_token"],
      )
      @creditcard = Creditcard.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @creditcard.save
        redirect_to creditcard_path(@creditcard.id)
      else
        redirect_to action: "new"
      end
    end
  end

  def destroy
    creditcard = Creditcard.where(user_id: current_user.id).last
    if creditcard.present?
      Payjp.api_key = ENV['PAYJP_ACCESS_KEY']
      customer = Payjp::Customer.retrieve(creditcard.customer_id)
      customer.delete
      creditcard.delete
    end
      redirect_to root_path
  end

  def show #cardのデータpayjpに送り情報を取り出す
    creditcard = Creditcard.where(user_id: current_user.id).last
    if creditcard.present?
      Payjp.api_key = ENV['PAYJP_ACCESS_KEY']
      customer = Payjp::Customer.retrieve(creditcard.customer_id)
      @default_card_information = customer.cards.retrieve(creditcard.card_id)
    end
  end

  def edit
  end

  def update
    @creditcard = Creditcard.find(params[:id])
    if @creditcard.update(creditcard_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def creditcard_params
    params.permit(:card_id, :exp_month, :exp_year, :cvc).merge(user_id: current_user.id)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @products = Product.includes(:images).order('created_at DESC').first(5)
  end
end

app/controllers/mypages_controller.rb
class MypagesController < ApplicationController
  def show
    @user = User.where(user_id: current_user.id)
  end

  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/creditcards_helper.rb
module CreditcardsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/creditcards/_header.html.haml
.header
  .title クレジットカード情報登録

app/views/creditcards/_link.html.haml
.edit
  .creditcard_edit
    = link_to creditcard_path(current_user), method: :get do
      クレジットカードの編集はこちら

app/views/creditcards/_title.html.haml
.header
  .title クレジットカード情報変更

app/views/creditcards/_update.html.haml
= form_with url:creditcard_path, method: :post, html: { name: "inputForm" },class:"form" do |f|
  .form__upper
    .form__upper__group
      = f.label :カード番号
      %span.form-require 必須
      = f.text_field :card_id, name: "card_id", id:"card_id", type: "string", placeholder: '半角数字のみ', class: 'input-default', maxlength: "16"
    .form__upper__group.exp
      .name
        = f.label :有効期限
        %span.form-require 必須
      %select#exp_year.card-default{name: "exp_year", type: "string"}
        %option{value: "2020"} 20
        %option{value: "2021"} 21
        %option{value: "2022"} 22
        %option{value: "2023"} 23
        %option{value: "2024"} 24
        %option{value: "2025"} 25
        %option{value: "2026"} 26
        %option{value: "2027"} 27
        %option{value: "2028"} 28
        %option{value: "2029"} 29
        %option{value: "2030"} 30
      %span 年
      %select#exp_month.card-default{name: "exp_month", type: "string"}
        %option{value: "1"} 01
        %option{value: "2"} 02
        %option{value: "3"} 03
        %option{value: "4"} 04
        %option{value: "5"} 05
        %option{value: "6"} 06
        %option{value: "7"} 07
        %option{value: "8"} 08
        %option{value: "9"} 09
        %option{value: "10"} 10
        %option{value: "11"} 11
        %option{value: "12"} 12
      %span 月
    .form__upper__group
      = f.label :セキュリティーコード
      %span.form-require 必須
      = f.text_field :cvc, name: "cvc", id:"cvc", class:"cvc", type: "text", placeholder: 'カード背面4桁もしくは3桁の番号', class: 'input-default', maxlength: "16"
    .form__upper__group
      = f.submit "登録", class: 'btn-default'

app/views/creditcards/application.html.haml
%html
  %head
    %meta{content: "text/html; charset=UTF-8", http: { equiv: "Content-Type" }}
    %title fleamarket_sample_78a
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
    %script{type:"text/javascript"},Payjp.setPublicKey('pk_test_fbb7b5276b50edbd22ac86f4');
  %body
   = yield

app/views/creditcards/edit.html.haml
= render 'title'
= render 'update'

app/views/creditcards/new.html.haml
.card__add
  .card__header
    .title クレジットカード情報登録
  -#createアクションに入力情報を渡す
  = form_tag(creditcards_path, method: :post, id: "charge-form", class: "details", name: "inputForm") do
    .number-details
      .card-number カード番号
      %span.must_check 必須
    .number
      = text_field_tag "payment_card_no", "", class: 'cardnumber', id: "payment_card_no", placeholder: '半角数字のみ', type: "text", maxlength: "16"
    .image
      = image_tag(image_path('cards/visa.jpg'), class: 'visa')
      = image_tag(image_path('cards/mc.png'), class: 'master')
      = image_tag(image_path('cards/jcb.gif'), class: 'jcb')
      = image_tag(image_path('cards/amex.gif'), class: 'amex')
      = image_tag(image_path('cards/diners.gif'), class: 'diners')
      = image_tag(image_path('cards/discover.jpg'), class: 'discover')

    .expirationdate
      .expirationdate__details
        .date 有効期限
        %span.must_check 必須
      .expirationdate__choice
        .month
          %select#payment_card_month.card-default{name: "payment_card_month", type: "text"} 
            %option{value: "1"} 01
            %option{value: "2"} 02
            %option{value: "3"} 03
            %option{value: "4"} 04
            %option{value: "5"} 05
            %option{value: "6"} 06
            %option{value: "7"} 07
            %option{value: "8"} 08
            %option{value: "9"} 09
            %option{value: "10"} 10
            %option{value: "11"} 11
            %option{value: "12"} 12
          .month-details 月
        .year
          %select#payment_card_year.card-default{name: "payment_card_year", type: "text"}
            %option{value: "2020"} 20
            %option{value: "2021"} 21
            %option{value: "2022"} 22
            %option{value: "2023"} 23
            %option{value: "2024"} 24
            %option{value: "2025"} 25
            %option{value: "2026"} 26
            %option{value: "2027"} 27
            %option{value: "2028"} 28
            %option{value: "2029"} 29
            %option{value: "2030"} 30
          .year-details 年

    .securitycode
      .securitycode__details
        .securitycode-details__title セキュリティコード
        %span.must_check 必須
      .securitycode__cardsecurity
        = text_field_tag "payment_card_cvc", "", type: 'text', class: 'securitycode__cardsecurity__form', id: "payment_card_cvc", maxlength: "4", placeholder: 'カード背面4桁もしくは3桁の番号'
      .card-question
    .add 
      = submit_tag "登録する", class: "add__btn", id: "payment_card_submit-button"

= render 'items/app_banner'
= render 'items/footer'

app/views/creditcards/show.html.haml
.card__add
  .card__header
    .title クレジットカード情報確認
  .card__info
    .card__info__number
      = "**** **** **** " + @default_card_information.last4
    .card__info__exp
      - exp_month = @default_card_information.exp_month.to_s
      - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
      = exp_month + " / " + exp_year
  .card-delete
    = form_tag(creditcard_path, method: :delete, id: 'charge-form', name: "inputForm") do
      %input{ type: "hidden", name: "card_id", value: "" }
      %button.delete-btn 削除する
  .top-page-btn
    = link_to root_path , class: "topPageBtn" do
      .top-page-btn-text
        トップページに戻る
        
= render 'items/app_banner'
= render 'items/footer'