config/routes.rb
Rails.application.routes.draw do
  get 'purchase/index'
  get 'purchase/done'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  root to: 'items#index'

  resources :users, only: [:index]
  resources :mypages, only: [:show, :index]
  resources :creditcards

  
  resources :products do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'purchase_check', to:'products#purchase_check'
      post 'purchase_completed', to:'products#purchase_completed'
      get 'done', to: 'products#done'
      get 'products/:id' => 'products#show'
      get 'purchase_completed'
    end
  end

  resources :addresses , only: [:new, :create ]

  # 削除済商品へのアクセスした場合のエラー画面を表示するためのルーティング
  get 'not_found', to:'products#not_found'

  # クレジットカード登録ページのルーティング
  get 'card', to:'mypages#card'

  end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user, optional: true
  validates :prefecture, :city, :house_number, presence: true
  validates :postnumber, presence: true,
  format: {
    with: /\A\d{3}[-]\d{4}\z/,
    message: "はハイフン(-)付き半角７桁で入力して下さい"
  }
  validates :first_name, :last_name, presence: true,
  format: {
    with: /\A[ぁ-んァ-ン一-龥]/,
    message: "は全角（ひらがな、カタカナ、漢字）のみで入力して下さい"
  }
  validates :first_name_kana, :last_name_kana, presence: true,
  format: {
    with: /\A[ァ-ヶー－]+\z/,
    message: "は全角カタカナのみで入力して下さい"
  }

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_ancestry
  has_many :products
end

app/models/creditcard.rb
class Creditcard < ApplicationRecord
  belongs_to :user

  validates :card_id, presence: true
  validates :user_id, presence: true
  validates :customer_id, presence: true

end

app/models/delivery_fee.rb
class DeliveryFee < ActiveHash::Base
  self.data = [
    {id: 1, name: '送料込み（出品者負担）'}, {id: 2, name: '着払い（購入者負担）'}
  ]
end

app/models/delivery_time.rb
class DeliveryTime < ActiveHash::Base
  self.data = [
    {id: 1, name: '1~2日で発送'}, {id:2, name: '2~3日で発送'},
    {id: 3, name: '4~7日で発送'}
  ]
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :product, optional: true
  mount_uploader :image, ImageUploader
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :images, dependent: :destroy
  belongs_to :category

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :size 
  belongs_to_active_hash :product_status 
  belongs_to_active_hash :delivery_fee 
  belongs_to_active_hash :delivery_time

  accepts_nested_attributes_for :images, allow_destroy: true
  validates_associated :images
  validates :images, presence: { message:"は1つ以上登録してください" }
  validates :product_name, length: { maximum: 40 }, presence: true
  validates :product_detail, presence: true
  validates :category_id, :size_id, :product_status_id, :delivery_area, :delivery_fee_id, :delivery_time_id, presence: { message: "を選択してください"}
  
  validates :price, inclusion: {in: 300..9999999, message: "は300~9,999,999の範囲で入力してください" }, presence: true

end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/product_status.rb
class ProductStatus < ActiveHash::Base
  self.data = [
    {id: 1, name: '新品、未使用'}, {id:2, name: '未使用に近い'},
    {id: 3, name: '目立った傷や汚れなし'}, {id:4, name: 'やや傷や汚れあり'},
    {id: 5, name: '傷や汚れあり'}, {id:6, name: '全体的に状態が悪い'}
  ]
end

app/models/size.rb
class Size < ActiveHash::Base
  self.data = [
    {id: 1, name: 'XXS以下'}, {id: 2, name: 'XS(SS)'},
    {id: 3, name: 'S'}, {id: 4, name: 'M'},
    {id: 5, name: 'L'}, {id: 6, name: 'XL(LL)'},
    {id: 7, name: '2XL(3L)'}, {id: 8, name: '3XL(4L)'},
    {id: 9, name: '4XL(5L)以上'}, {id: 10, name: 'FREE SIZE'}
  ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, :birthday, presence: true
  validates :first_name, :last_name, presence: true,
    format: {
      with: /\A[ぁ-んァ-ン一-龥]/,
      message: "は全角（ひらがな、カタカナ、漢字）のみで入力して下さい"
    }
  validates :first_name_kana, :last_name_kana, presence: true,
    format: {
      with: /\A[ァ-ヶー－]+\z/,
      message: "は全角カタカナのみで入力して下さい"
    }

    has_one :address
    has_many :products
    has_many :creditcards
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @products = Product.includes(:images).order('created_at DESC').first(5)
  end
end

app/controllers/mypages_controller.rb
class MypagesController < ApplicationController
  def show
    @user = User.where(user_id: current_user.id)
  end

  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/creditcards_helper.rb
module CreditcardsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_display_btn.html.haml
= link_to new_product_path, class: "display_btn" do
  .display_btn__in-box
    .display_btn__in-box--text
      出品する
    = image_tag "icon/icon_camera.png", size: "54x54", class: "display_btn__in-box--img"

app/views/items/_header.html.haml
.header__box
  .header__box__main
    .main__icon
      = link_to root_path do
        = image_tag 'logo/logo.png', alt: 'title', height: '41', width: '140'
    .main__search
      = form_with(url: "#", local: true, method: :get, class: "search-form") do |form|
        = form.text_field :keyword, placeholder: "キーワードから探す", class: "search-input"
        = button_tag type: "submit", class: "search-btn" do
          %i.fas.fa-search.fa-lg
  .header__box__action

    %ul.action__list
      %li.list__category
        = link_to "#" do
          カテゴリー

      %li.list__brand
        = link_to "#" do
          ブランド

    - if user_signed_in?
      .action__user     
        = link_to 'マイページ', mypage_path(:current_user), class: "mypage_btn"
    - else
      %ul.action__user
        %li.user__login
          = link_to new_user_session_path, class: "login_btn" do
            ログイン
        %li.user__new
          = link_to new_user_registration_path, class: "new_btn" do
            新規会員登録

app/views/items/_main_visual.html.haml
.main_visual_create-one
  .main_visual_create-one__body-main
    .main_visual_create-one__body-main--top
      %p 人生を変えるフリマアプリ
    .main_visual_create-one__body-main--middle
      %p FURIMAはだれでもかんたんに出品・購入できる
      %p フリマアプリです
    .main_visual_create-one__body-main--btn
      = link_to "#", class: "iconApp" do
        = image_tag 'bag_app.png',class: "appBtn"
      = link_to "#", class: "iconGoogle" do
        = image_tag 'ja_badge_web_generic.png',class: "googleBtn"

app/views/items/_pickup_brand.html.haml
.wrapper
  .pickup_brand__containerBrand
    %h2.pickup_brand__containerBrand__title
      ピックアップブランド
    .pickup_brand__containerBrand__product
      .pickup_brand__containerBrand__product__head
        = link_to "#", class: "pickup_brand__products--head" do
          %h3.pickup_brand__head アーカイバ
      .pickup_brand__containerBrand__product--lists
        
        .pickup_brand__containerBrand__product--lists__list
          = link_to product_path(1) do
            %figure.pickup_brand__product__images
              = image_tag 'https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/18/beef.JPG', alt: "image_url", class:"pickup_brand__product__images--image"
          .pickup_brand__containerBrand__product--lists__list__body
            %h3.pickup_brand__product--name
              fuga1
            .pickup_brand__containerBrand__product--lists__list__body__details
              %ul.pickup_brand__details__menu
                %li
                  100円
                %li ★1
            %p.pickup_brand__taxIncluded （税込）
        .pickup_brand__containerBrand__product--lists__list
          %figure.pickup_brand__product__images
            = image_tag 'https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/16/IMG_9072.JPG', alt: "image_url", class:"pickup_brand__product__images--image"
          .pickup_brand__containerBrand__product--lists__list__body
            %h3.pickup_brand__product--name
              fuga2
            .pickup_brand__containerBrand__product--lists__list__body__details
              %ul.pickup_brand__details__menu
                %li
                  200円
                %li ★2
            %p.pickup_brand__taxIncluded （税込）
        .pickup_brand__containerBrand__product--lists__list
          %figure.pickup_brand__product__images
            = image_tag 'https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/13/a007.png',alt: "image_url", class:"pickup_brand__product__images--image"
          .pickup_brand__containerBrand__product--lists__list__body
            %h3.pickup_brand__product--name
              fuga3
            .pickup_brand__containerBrand__product--lists__list__body__details
              %ul.pickup_brand__details__menu
                %li
                  300円
                %li ★3
            %p.pickup_brand__taxIncluded （税込）
        .pickup_brand__containerBrand__product--lists__list
          %figure.pickup_brand__product__images
            = image_tag 'https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/10/a004.png',alt: "image_url", class:"pickup_brand__product__images--image"
          .pickup_brand__containerBrand__product--lists__list__body
            %h3.pickup_brand__product--name
              fuga4
            .pickup_brand__containerBrand__product--lists__list__body__details
              %ul.pickup_brand__details__menu
                %li
                  400円
                %li ★4
            %p.pickup_brand__taxIncluded （税込）
        .pickup_brand__containerBrand__product--lists__list
          %figure.pickup_brand__product__images
            = image_tag 'https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/7/a001.png',alt: "image_url", class:"pickup_brand__product__images--image"
          .pickup_brand__containerBrand__product--lists__list__body
            %h3.pickup_brand__product--name
              fuga5
            .pickup_brand__containerBrand__product--lists__list__body__details
              %ul.pickup_brand__details__menu
                %li
                  500円
                %li ★5
            %p.pickup_brand__taxIncluded （税込）

app/views/items/_pickup_category.html.haml
.wrapper
  .pickup_category__containerCategory
    %h2.pickup_category__containerCategory__title
      ピックアップカテゴリー
    .pickup_category__containerCategory__product
      .pickup_category__containerCategory__product--head
        = link_to "products", class: "pickup_category__products--head" do
          %h3.products--head-title 新規投稿商品
      .pickup_category__containerCategory__product--lists
        - @products.each do |product|
          -if product.trading_status == 2
            .pickup_category__containerCategory__product--lists__list
              = link_to product_path(product) do
                %figure.pickup_category__product__images
                  -# 商品一覧実装時はテスト画像利用のためコメントアウト。次回実装時にお使いくださいませ。
                  = image_tag product.images.first.image.url
                  -# = image_tag 'T-shirt.png',alt: "image_url", class:"pickup_brand__product__images--image"
                .pickup_category__containerCategory__product--lists__list--body
                  %h3.pickup_category__product--name
                    = product.product_name
                  .pickup_category__containerCategory__product--lists__list--body__details
                    %ul.pickup_category__details__menu
                      %li
                        = product.price.to_s(:delimited)
                        円
                      %li
                        = icon('fa', 'star')
                        0
                  %p.pickup_category__taxIncluded (税込)
                .pickup_category__containerCategory__product--lists__list__sold
                  .pickup_category__containerCategory__product--lists__list__sold__inner
                    sold
          - else
            .pickup_category__containerCategory__product--lists__list
              = link_to product_path(product)  do
                %figure.pickup_category__product__images
                  -# 商品一覧実装時はテスト画像利用のためコメントアウト。次回実装時にお使いくださいませ。
                  = image_tag product.images.first.image.url
                  -# = image_tag 'TankTop.png',alt: "image_url", class:"pickup_brand__product__images--image"
                .pickup_category__containerCategory__product--lists__list--body
                  %h3.pickup_category__product--name
                    = product.product_name
                  .pickup_category__containerCategory__product--lists__list--body__details
                    %ul.pickup_category__details__menu
                      %li
                        = product.price.to_s(:delimited)
                        円
                      %li
                        = icon('fa', 'star')
                        0
                  %p.pickup_category__taxIncluded (税込)

app/views/items/_top_introduction.html.haml
.top_introduction__box
  .top_introduction__box__top
    .top_introduction__box__top--title
      FURIMAが選ばれる3つの理由
    .top_introduction__box__top--line
  %ul.top_introduction__box__mains
    %li.top_introduction__box__mains__main
      = image_tag "pict/pict-reason-01.jpg", class: "top-img"
      .top_introduction__box__mains__main--sub-title
        .top_introduction__box__mains__main--sub-title--green
          3分
          %span.top_introduction__box__mains__main--sub-title--black
            ですぐに出品
      %p.top_introduction__box__mains__main--text
        スマホで入力するだけで簡単に出品できる！
      .top_introduction__box__mains__main--num
        1
    %li.top_introduction__box__mains__main
      = image_tag "pict/pict-reason-02.jpg", class: "top-img"
      .top_introduction__box__mains__main--sub-title
        .top_introduction__box__mains__main--sub-title--green
          シンプル
          %span.top_introduction__box__mains__main--sub-title--black
            で使いやすい
      %p.top_introduction__box__mains__main--text
        めんどくさい入力は必要なく、検索も購入もスムーズ！
      .top_introduction__box__mains__main--num
        2
    %li.top_introduction__box__mains__main-right
      = image_tag "pict/pict-reason-03.jpg", class: "top-img"
      .top_introduction__box__mains__main--right--sub-title
        .top_introduction__box__mains__main--sub-title--black
          手数料
          %span.top_introduction__box__mains__main--sub-title--green
            業界最安
      %p.top_introduction__box__mains__main-right--text
        最大3%でお得に出品&購入！
      .top_introduction__box__mains__main-right--num
        3

app/views/items/_top_key_features.html.haml
.wrapper
  .top_key_features__containerFeatures
    %h2.top_key_features__head__title
      FURIMAの特徴
    .top_key_features__containerFeatures__items
      .top_key_features__containerFeatures__items__list
        %figure.top_key_features__containerFeatures__images
          = image_tag "icon/icon-01.png", class: "top_key_features__containerFeatures__images__image"
        %h3.top_key_features__item__subtitle
          簡単に売り買いできる
        %p.top_key_features__item__detail
          スマホ１つで、いつでもどこでも簡単に出品、購入が可能！
      .top_key_features__containerFeatures__items__list
        %figure.top_key_features__containerFeatures__images
          = image_tag "icon/icon-03.png", class: "top_key_features__containerFeatures__images__image"
        %h3.top_key_features__item__subtitle
          売上金は即日振り込みに対応
        %p.top_key_features__item__detail
          午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
      .top_key_features__containerFeatures__items__list
        %figure.top_key_features__containerFeatures__images
          = image_tag "icon/icon-04.png", class: "top_key_features__containerFeatures__images__image"
        %h3.top_key_features__item__subtitle
          様々な支払いに対応
        %p.top_key_features__item__detail
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。

app/views/items/_top_middle_DL.html.haml
.top_middle__block
  .top_middle__block__in-box
    .top_middle__block__in-box__title
      会員数日本一位
    .top_middle__block__in-box__text
      .top_middle__block__in-box__text--1
        FURIMAは、フリマアプリで最も人気。
      .top_middle__block__in-box__text--2
        出品・購入回数も業界最多です！
      .top_middle__block__in-box__text--3
        欲しかったあの商品に出会えるかもしれません。
    .top_middle__block__in-box__icon
      = link_to "#", class: "in-box__icon" do
        = image_tag 'bag_app.png',class: "appBtn"
      = link_to "#", class: "in-box__icon" do
        = image_tag 'ja_badge_web_generic.png',class: "googleBtn"

app/views/items/index.html.haml
= render 'header'
= render 'main_visual'
= render 'top_introduction'
= render 'top_middle_DL'
= render 'top_key_features'
= render 'pickup_category'
= render 'pickup_brand'
= render 'display_btn'
= render 'app_banner'
= render 'footer'

app/views/mypages/_app_banner.html.haml
.wrapper
  .app_banner__banner
    %section.app_banner__banner__image
    .app_banner__banner__inner
      %h2.app_banner__banner__inner--title
        だれでも簡単、人生を変えるフリマアプリ
      %p.app_banner__banner__inner--text
        今すぐ無料ダウンロード
      .app_banner__banner__inner--icon
        = link_to "#", class: "app_banner__banner__inner--icon" do
          = image_tag 'bag_app.png',class: "appBtn"
        = link_to "#", class: "app_banner__banner__inner--icon" do
          = image_tag 'ja_badge_web_generic.png',class: "googleBtn"

app/views/mypages/_footer.html.haml
.wrapper
  .home_footer__footer
    .home_footer__footer__contents
      %li.home_footer__footer__contents__list
        %h2.home_footer__footer__contents__list--title FURIMAについて
        %ul.home_footer__footer__contents__list--menu
          %li.home_footer
            = link_to "#", class: "home_footer__list--menu" do
              = "会社概要（運営会社）"
          %li
            = link_to "#", class: "home_footer__list--menu" do
              = "プライバシーポリシー"
          %li
            = link_to "#", class: "home_footer__list--menu" do
              = "FURIMA利用規約"
          %li
            = link_to "#", class: "home_footer__list--menu" do
              = "ポイントに関する特約"
      %li.home_footer__footer__contents__list
        %h2.home_footer__footer__contents__list--title FURIMAを見る
        %ul.home_footer__footer__contents__list--menu
          %li
            = link_to "#", class: "home_footer__list--menu" do
              = "カテゴリ一一覧"
          %li
            = link_to "#", class: "home_footer__list--menu" do
              = "ブランド一覧"
      %li.home_footer__footer__contents__list
        %h2.home_footer__footer__contents__list--title ヘルプ＆ガイド
        %ul.home_footer__footer__contents__list--menu
          %li
            = link_to "#", class: "home_footer__list--menu" do
              = "FURIMAガイド"
          %li
            = link_to "#", class: "home_footer__list--menu" do
              = "FURIMAロゴ利用ガイドライン"
          %li
            = link_to "#", class: "home_footer__list--menu" do
              = "お知らせ"
    .home_footer__footer__logo
      = link_to "#", class: "home_footer__list--menu" do
        = image_tag "logo/logo-white.png", alt:"フッターのロゴ", class: "home_footer__footer__logo__white"
      %p FURIMA

app/views/mypages/_header.html.haml
.header__box
  .header__box__main
    .main__icon
      = link_to root_path do
        = image_tag 'logo/logo.png', alt: 'title', height: '41', width: '140'

  .header__box__action
    .creditcard
      = link_to new_creditcard_path do
        クレジットカード登録・確認・削除
    .action__user     
      = link_to 'ログアウト', mypages_path

app/views/mypages/_logout.html.haml
.logoutpage
  .registration-title
    ログアウトが完了しました。
  .return-toppage
    = link_to 'トップページに戻る', destroy_user_session_path, method: :delete

app/views/mypages/_mainpage.html.haml
.mainpage
  %ul
    %li.usericon
      = icon('fas', 'user fa-4x')
    %li.username 
      =current_user.nickname

app/views/mypages/index.html.haml
= render 'logout'

app/views/mypages/show.html.haml
= render 'header'
= render 'mainpage'
= render 'app_banner'
= render 'footer'