config/routes.rb
Rails.application.routes.draw do
  get 'purchase/index'
  get 'purchase/done'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  root to: 'items#index'

  resources :users, only: [:index]
  resources :mypages, only: [:show, :index]
  resources :creditcards

  
  resources :products do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'purchase_check', to:'products#purchase_check'
      post 'purchase_completed', to:'products#purchase_completed'
      get 'done', to: 'products#done'
      get 'products/:id' => 'products#show'
      get 'purchase_completed'
    end
  end

  resources :addresses , only: [:new, :create ]

  # 削除済商品へのアクセスした場合のエラー画面を表示するためのルーティング
  get 'not_found', to:'products#not_found'

  # クレジットカード登録ページのルーティング
  get 'card', to:'mypages#card'

  end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user, optional: true
  validates :prefecture, :city, :house_number, presence: true
  validates :postnumber, presence: true,
  format: {
    with: /\A\d{3}[-]\d{4}\z/,
    message: "はハイフン(-)付き半角７桁で入力して下さい"
  }
  validates :first_name, :last_name, presence: true,
  format: {
    with: /\A[ぁ-んァ-ン一-龥]/,
    message: "は全角（ひらがな、カタカナ、漢字）のみで入力して下さい"
  }
  validates :first_name_kana, :last_name_kana, presence: true,
  format: {
    with: /\A[ァ-ヶー－]+\z/,
    message: "は全角カタカナのみで入力して下さい"
  }

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_ancestry
  has_many :products
end

app/models/creditcard.rb
class Creditcard < ApplicationRecord
  belongs_to :user

  validates :card_id, presence: true
  validates :user_id, presence: true
  validates :customer_id, presence: true

end

app/models/delivery_fee.rb
class DeliveryFee < ActiveHash::Base
  self.data = [
    {id: 1, name: '送料込み（出品者負担）'}, {id: 2, name: '着払い（購入者負担）'}
  ]
end

app/models/delivery_time.rb
class DeliveryTime < ActiveHash::Base
  self.data = [
    {id: 1, name: '1~2日で発送'}, {id:2, name: '2~3日で発送'},
    {id: 3, name: '4~7日で発送'}
  ]
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :product, optional: true
  mount_uploader :image, ImageUploader
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :images, dependent: :destroy
  belongs_to :category

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :size 
  belongs_to_active_hash :product_status 
  belongs_to_active_hash :delivery_fee 
  belongs_to_active_hash :delivery_time

  accepts_nested_attributes_for :images, allow_destroy: true
  validates_associated :images
  validates :images, presence: { message:"は1つ以上登録してください" }
  validates :product_name, length: { maximum: 40 }, presence: true
  validates :product_detail, presence: true
  validates :category_id, :size_id, :product_status_id, :delivery_area, :delivery_fee_id, :delivery_time_id, presence: { message: "を選択してください"}
  
  validates :price, inclusion: {in: 300..9999999, message: "は300~9,999,999の範囲で入力してください" }, presence: true

end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/product_status.rb
class ProductStatus < ActiveHash::Base
  self.data = [
    {id: 1, name: '新品、未使用'}, {id:2, name: '未使用に近い'},
    {id: 3, name: '目立った傷や汚れなし'}, {id:4, name: 'やや傷や汚れあり'},
    {id: 5, name: '傷や汚れあり'}, {id:6, name: '全体的に状態が悪い'}
  ]
end

app/models/size.rb
class Size < ActiveHash::Base
  self.data = [
    {id: 1, name: 'XXS以下'}, {id: 2, name: 'XS(SS)'},
    {id: 3, name: 'S'}, {id: 4, name: 'M'},
    {id: 5, name: 'L'}, {id: 6, name: 'XL(LL)'},
    {id: 7, name: '2XL(3L)'}, {id: 8, name: '3XL(4L)'},
    {id: 9, name: '4XL(5L)以上'}, {id: 10, name: 'FREE SIZE'}
  ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, :birthday, presence: true
  validates :first_name, :last_name, presence: true,
    format: {
      with: /\A[ぁ-んァ-ン一-龥]/,
      message: "は全角（ひらがな、カタカナ、漢字）のみで入力して下さい"
    }
  validates :first_name_kana, :last_name_kana, presence: true,
    format: {
      with: /\A[ァ-ヶー－]+\z/,
      message: "は全角カタカナのみで入力して下さい"
    }

    has_one :address
    has_many :products
    has_many :creditcards
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @products = Product.includes(:images).order('created_at DESC').first(5)
  end
end

app/controllers/mypages_controller.rb
class MypagesController < ApplicationController
  def show
    @user = User.where(user_id: current_user.id)
  end

  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  require 'payjp'
  before_action :set_product, only: [:show, :destroy, :edit, :update, :purchase_check, :purchase_completed]

  def index
    @products = Product.includes(:images).order('created_at DESC')
  end

  def new
    @product = Product.new
    @product.images.new

    @category_parent_array = ["---"]
    @category_parent_array = Category.where(ancestry: nil)
    unless user_signed_in?
      redirect_to new_user_session_path
    end
  end

  def edit
    @product.images.new
    
    @category_parent_array = ["---"]
    @category_parent_array = Category.where(ancestry: nil)
  end

  def update
    if @product.update(product_params)
      redirect_to product_path(@product.id)
    else
      redirect_to action: :edit
    end
  end

  def create
     @product = Product.new(product_params)
     if @product.save
       redirect_to root_path
     else
       @product.images.new
       render :new
     end
  end

  def show
    @product_s = Product.find(params[:id])
  end

  def destroy
    flash.now[:alert] = '削除に失敗しました' unless @product.destroy  
  end

  def get_category_children
    @category_children = Category.find("#{params[:parent_id]}").children
  end

  def get_category_grandchildren
    @category_grandchildren = Category.find(params[:child_id]).children
  end

  # 購入確認ページへ遷移
  def purchase_check
    @product_s = Product.find(params[:id])
    creditcard = Creditcard.where(user_id: current_user.id).last
    if creditcard.blank?
      redirect_to controller: "creditcards", action: "new"
    else
      Payjp.api_key = ENV['PAYJP_ACCESS_KEY']
      customer = Payjp::Customer.retrieve(creditcard.customer_id)
      @default_card_information = customer.cards.retrieve(creditcard.card_id)
    end
  end

  # 購入完了ページに遷移
  def purchase_completed
    @product_s = Product.find(params[:id])
    creditcard = Creditcard.where(user_id: current_user.id).last
    Payjp.api_key = ENV['PAYJP_ACCESS_KEY']
    Payjp::Charge.create(
    :amount => @product_s.price,
    :customer => creditcard.customer_id, #顧客ID
    :currency => 'jpy', #日本円
    )
    @product.update(trading_status: 2)
    redirect_to done_product_path(@product)
  
  end

  def done
    @product_s = Product.find(params[:id])
    creditcard = Creditcard.where(user_id: current_user.id).last
    Payjp.api_key = ENV['PAYJP_ACCESS_KEY']
    customer = Payjp::Customer.retrieve(creditcard.customer_id)
    @default_card_information = customer.cards.retrieve(creditcard.card_id)
  end
  
  private

  def set_product
    # レコードの存在を確認し、なければnot_foundを返す
    if Product.exists?(params[:id])
      @product = Product.find(params[:id])
    else
      redirect_to not_found_path
    end  
  end

  def product_params
    params.require(:product).permit(:product_name, :product_detail, :category_id, :brand, :delivery_area, :price, :size_id, :product_status_id, :delivery_fee_id, :delivery_time_id, :trading_status,images_attributes: [:image, :id, :_destory]).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/creditcards_helper.rb
module CreditcardsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/_error_messages.html.haml
-if @product.errors.any? 
  .alert
    %ul
      -@product.errors.full_messages.each do |message| 
        %li= message

app/views/products/_product_listing.html.haml
= form_with model: @product do |f|
  = f.text_field :product_name, placeholder: "商品名"
  = f.text_field :product_detail, placeholder: "説明文"

  #image-box
    #previews
      - if @product.persisted?
        - @product.images.each_with_index do |image, i|
          = image_tag image.src.url, data: { index: i }, width: "100", height: '100'
    = f.fields_for :images do |image|
      .js-file_group{"data-index" => "#{image.index}"}
        = image.file_field :image, class: "js-file"
        %br/
        %span.js-remove 削除
      - if @product.persisted?
        = image.check_box :_destroy, data:{ index: image.index }, class: 'hidden-destroy'

  = f.select :category, [["カテゴリー（仮）", 0], ["レディース", 1], ["メンズ", 2], ["ベビー・キッズ", 3], ["インテリア・住まい・子供", 4]]
  = f.text_field :brand, placeholder: "ブランド"
 
  = f.number_field :price, placeholder: "価格"

  = f.collection_select :size_id, Size.all, :id, :name, prompt: "サイズ"
  = f.collection_select :product_status_id, ProductStatus.all, :id, :name, prompt: "商品状態"
  = f.select :delivery_area, ["北海道","青森県","岩手県","宮城県","秋田県","山形県","福島県","茨城県","栃木県","群馬県","埼玉県","千葉県","東京都","神奈川県","新潟県","富山県","石川県","福井県","山梨県","長野県","岐阜県","静岡県","愛知県","三重県","滋賀県","京都府","大阪府","兵庫県","奈良県","和歌山県","鳥取県","島根県","岡山県","広島県","山口県","徳島県","香川県","愛媛県","高知県","福岡県","佐賀県","長崎県","熊本県","大分県","宮崎県","鹿児島県","沖縄県","未定"]
  = f.collection_select :delivery_fee_id, DeliveryFee.all, :id, :name, prompt: "送料"
  = f.collection_select :delivery_time_id, DeliveryTime.all, :id, :name, prompt: "発送までの日数"

  = f.submit "登録"

app/views/products/destroy.html.haml
.entire_box
  .new__page__header
    = link_to image_tag("logo/logo.png", alt: "logo"), root_path

  .product-delete-field
    .product-delete-field__text
      商品の削除が完了しました。
    .product-delete-field__link
      = link_to 'トップページに戻る', root_path 

app/views/products/done.html.haml
.contents
  .contents__logo
    .contents__logo__FURIMA
      = link_to root_path do
        = image_tag 'logo/logo.png', alt: 'logo', class: 'top-logo'
  .contents__send
    .contents__send__waiting
      .contents__send__waiting__confirm
        %ul.text
          %li.text1
            %b 発送をお待ちください
          %li.text2
            %b 出品者からの発送通知をお待ちください
  .contents__detail
    .contents__detail__title
      .contents__detail__title__confirm
        %b 購入内容の確認
    .contents__detail__pic
      .contents__detail__pic__confirm
        = image_tag @product_s.images.first.image.url, class: 'beef-pic'
    .contents__detail__price
      .contents__detail__price__confirm
        %b 支払い金額
        ¥
        = @product_s.price
    .contents__detail__method
      .contents__detail__method__confirm
        %b 支払い方法
        - if @default_card_information.blank?
          %br /
        - else
          = "**** **** **** " + @default_card_information.last4
          - exp_month = @default_card_information.exp_month.to_s
          - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
          = exp_month + " / " + exp_year
    .contents__detail__address
      .contents__detail__address__confirm
        %b 配送先
    .contents__detail__check
      .contents__detail__check__message
        %p 商品の購入後は、取引画面で配送状況の確認や
        %p メッセージのやりとりができます。
    .contents__detail__buy
      = link_to root_path , class: "buyBtn" do
        .contents__detail__buy__confirm
          トップページへ戻る
  .contents__footer
    .contents__footer__code
      %ul.lists
        %li.list プライバシーポリシー
        %li.list FURIMA利用規約
        %li.list 特定商取引に関する表記
    .contents__footer__logo
      .contents__footer__logo__rights
        = image_tag 'logo/logo-white.png', alt: 'logo-white', class: 'footer-logo'
      .contents__footer__logo__text
        ©︎FURIMA

app/views/products/edit.html.haml
- if user_signed_in? 
  = form_with model: @product, local:true do |f|
    = render 'error_messages'
    .entire_box
      .new__page__header
        = link_to image_tag("logo/logo.png", alt: "logo"), root_path
      .product__field
        .product__field__box
          .product__label
            .product__label__name      
              出品画像
            .product__label__required
              必須
            .product__label__text
              ※最大5枚までアップロードできます
          .form-image
            = f.fields_for :images do |image|
              .image_file_box
                // 写真のプレビューとインプットボタンのul
                %ul#previews
                  - @product.images.each do |image|
                    -if image.persisted?
                      %li.image-preview
                        = image_tag image.image.url
                        .image-preview_btn
                          .image-preview_btn_delete
                            削除
                  %li.input
                    // 画像を取り込むインプットボタン
                    %label.upload-label
                      .upload-label__text
                        ファイルをアップロード
                      .input-area
                        = icon('fas fa', 'camera', class:'image-icon')
                        = image.file_field :image, class: "hidden image_upload"

        .product__name__box
          .product__textField
            .product__textField__name      
              商品名
            .product__textField__required
              必須
          -# = text_field_tag "product_name", "", {class: "product_field",placeholder: "40字まで"}
          = f.text_field :product_name, placeholder: "40字まで", class: "product_field", required: "required"
        .product__explanation__box
          .product__explanationField
            .product__explanationField__name      
              商品の説明
            .product__explanationField__required
              必須
          = f.text_area :product_detail, placeholder:  "商品の説明（必須 1,000文字以内）\n（色、素材、重さ、定価、注意点など）\n\n例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。\n  ", rows: "7", class: "style_textarea"
        .product__category__box
          .product__details
            商品の詳細
            .product__categoryField
              .product__categoryField__name      
                カテゴリー
              .product__categoryField__required
                必須
            .category__styleSelect
              .category__styleSelect__selectarea
                = f.collection_select :category, Category.where(ancestry: nil), :id, :name, {prompt: '---', selected: @product.category.root_id}, {id: 'parent_category'}
              .category__styleSelect__selectarea__list#children_wrapper
                = f.collection_select :category, @product.category.parent.siblings, :id, :name, {prompt: '---', selected: @product.category.parent_id}, {id: 'child_category'}
              .category__styleSelect__selectarea__two#grandchildren_wrapper
                = f.collection_select :category_id, @product.category.siblings, :id, :name , {prompt: '---', selected: @product.category_id}, {id: 'grandchild_category'}
        .product__brand__box
          .product__brandField
            .product__brandField__name      
              ブランド
            .product__brandField__required
              任意
          = text_field "brand_name", "", {class: "brand_field",placeholder: "例） シャネル"}
        .product__status__box
          .product__statusField
            .product__statusField__name      
              商品の状態
            .product__statusField__required
              必須
          .category__statusSelect
            .category__statusSelect__selectarea
              = f.collection_select :product_status_id, ProductStatus.all, :id, :name, prompt: "選択してください", required: "required"
        .product__size__box
          .product__sizeField
            .product__sizeField__name      
              サイズ
            .product__sizeField__required
              必須
          .category__sizeSelect
            .category__sizeSelect__selectarea
              = f.collection_select :size_id, Size.all, :id, :name, prompt: "選択してください", required: "required"
        .product__delivery__box
          .product__regardingDelivery
            配送について
            .product__deliveryField
              .product__deliveryField__name      
                配送料の負担
              .product__deliveryField__required
                必須
            .delivery__styleSelect
              .delivery__styleSelect__selectarea
                = f.collection_select :delivery_fee_id, DeliveryFee.all, :id, :name, prompt: "選択してください", required: "required"
        .product__area__box
          .product__areaField
            .product__areaField__name      
              発送元の地域
            .product__areaField__required
              必須
          .category__areaSelect
            .category__areaSelect__selectarea
              = f.select :delivery_area, ["北海道","青森県","岩手県","宮城県","秋田県","山形県","福島県","茨城県","栃木県","群馬県","埼玉県","千葉県","東京都","神奈川県","新潟県","富山県","石川県","福井県","山梨県","長野県","岐阜県","静岡県","愛知県","三重県","滋賀県","京都府","大阪府","兵庫県","奈良県","和歌山県","鳥取県","島根県","岡山県","広島県","山口県","徳島県","香川県","愛媛県","高知県","福岡県","佐賀県","長崎県","熊本県","大分県","宮崎県","鹿児島県","沖縄県","未定"], { include_blank: true, selected: @product.delivery_area,required: "required" },{id: "delivery_area", class: "sell-collection_select__input", prompt: "選択してください"}
        .product__shippingDays__box
          .product__shippingDaysField
            .product__shippingDaysField__name      
              発送までの日数
            .product__shippingDaysField__required
              必須
          .category__shippingDaysSelect
            .category__shippingDaysSelect__selectarea
              = f.collection_select :delivery_time_id, DeliveryTime.all, :id, :name, prompt: "選択してください"
        .product__price__box
          .product__priceRange
            価格（¥300〜9,999,999）
            .product__priceField
              .product__priceField__box
                .product__priceField__box__name      
                  販売価格
                .product__priceField__box__required
                  必須
              .test
                .product__price__yen
                  ￥
                .product__priceRangeBox
                  .product__priceRangeBox__inputarea
                    = f.number_field :price, placeholder: "入力してください"
        .product__submitBotton__box
          .product__submitBottonField
            = f.submit "編集する", class:'product__submitBottonField__button'

app/views/products/not_found.html.haml
.entire_box
  .new__page__header
    = link_to image_tag("logo/logo.png", alt: "logo"), root_path

  .product-error-field
    .product-error-field__text
      ＜Not_Found＞お探しのページは見つかりませんでした。
    .product-error-field__detail
      この商品は削除された可能性があります。
      %br
      お手数ですが、トップページから操作をやり直してください。
    .product-error-field__link
      = link_to 'トップページに戻る', root_path 

app/views/products/purchase_check.html.haml
.contents
  .contents__logo
    .contents__logo__FURIMA
      = link_to "root_path" do
        = image_tag 'logo/logo.png', alt: 'logo', class: 'top-logo'
  .contents__detail
    .contents__detail__title
      .contents__detail__title__confirm
        %b 購入内容の確認
    .contents__detail__pic
      .contents__detail__pic__confirm
        = image_tag @product_s.images.first.image.url, class: 'beef-pic'
    .contents__detail__price
      .contents__detail__price__confirm
        %span.price
          %b 支払い金額
          ¥
          = @product_s.price
    .contents__detail__method
      .contents__detail__method__confirm
        %b 支払い方法
        - if @default_card_information.blank?
          %br /
        - else
          = "**** **** **** " + @default_card_information.last4
          - exp_month = @default_card_information.exp_month.to_s
          - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
          = exp_month + " / " + exp_year
    .contents__detail__address
      .contents__detail__address__confirm
        %b 配送先
    .contents__detail__caution
      .contents__detail__caution__confirm
        郵便局/コンビニ受取をご希望の方は、購入後に取引画面から受取場所を変更をすることが可能です。出品者が発送作業を開始した後は受取場所の変更ができませんので、早めに変更を行ってください。
    .contents__detail__buy
      = link_to purchase_completed_product_path(@product), method: :post do
        %button.contents__detail__buy__confirm
          購入する
  .contents__footer
    .contents__footer__code
      %ul.lists
        %li.list プライバシーポリシー
        %li.list FURIMA利用規約
        %li.list 特定商取引に関する表記
    .contents__footer__logo
      .contents__footer__logo__rights
        = image_tag 'logo/logo-white.png', alt: 'logo-white', class: 'footer-logo'
      .contents__footer__logo__text
        ©︎FURIMA

app/views/products/purchase_completed.html.haml
.contents
  .contents__logo
    .contents__logo__FURIMA
      = link_to root_path do
        = image_tag 'logo/logo.png', alt: 'logo', class: 'top-logo'
  .contents__send
    .contents__send__waiting
      .contents__send__waiting__confirm
        %ul.text
          %li.text1
            %b 発送をお待ちください
          %li.text2
            %b 出品者からの発送通知をお待ちください
  .contents__detail
    .contents__detail__title
      .contents__detail__title__confirm
        %b 購入内容の確認
    .contents__detail__pic
      .contents__detail__pic__confirm
        = image_tag 'pict/beef.jpg', alt: 'beef', class: 'beef-pic'
    .contents__detail__price
      .contents__detail__price__confirm
        %b 支払い金額
    .contents__detail__method
      .contents__detail__method__confirm
        %b 支払い方法
    .contents__detail__address
      .contents__detail__address__confirm
        %b 配送先
    .contents__detail__check
      .contents__detail__check__message
        %p 商品の購入後は、取引画面で配送状況の確認や
        %p メッセージのやりとりができます。
    .contents__detail__buy
      = link_to root_path , class: "buyBtn" do
        .contents__detail__buy__confirm
          取引画面をみる
  .contents__footer
    .contents__footer__code
      %ul.lists
        %li.list プライバシーポリシー
        %li.list FURIMA利用規約
        %li.list 特定商取引に関する表記
    .contents__footer__logo
      .contents__footer__logo__rights
        = image_tag 'logo/logo-white.png', alt: 'logo-white', class: 'footer-logo'
      .contents__footer__logo__text
        ©︎FURIMA

app/views/products/show.html.haml
.header__box
  .header__box__main
    .main__icon
      = link_to root_path do
        = image_tag 'logo/logo.png', alt: 'title', height: '41', width: '140'
    .main__search
      = form_with(url: "#", local: true, method: :get, class: "search-form") do |form|
        = form.text_field :keyword, placeholder: "キーワードから探す", class: "search-input"
        = button_tag type: "submit", class: "search-btn" do
          %i.fas.fa-search.fa-lg
  .header__box__action

    %ul.action__list
      %li.list__category
        = link_to "#" do
          カテゴリー

      %li.list__brand
        = link_to "#" do
          ブランド
    %ul.action__user
      %li.user__login
        = link_to root_path, class: "login_btn" do
          ログイン
      %li.user__new
        = link_to root_path, class: "new_btn" do
          新規会員登録

.breadcrumbs
  %ul.breadcrumbs__test
    %li.link
      =link_to "#", class: "link__text" do
        FURIMA
    %li.link
      = icon("fa", "angle-right")
    %li.link
      =link_to "#", class: "link__text" do
        = @product_s.category.root.name
    %li.link
      = icon("fa", "angle-right")
    %li.link
      =link_to "#", class: "link__text" do
        = @product_s.category.parent.name
    %li.link
      = icon("fa", "angle-right")
    %li.link
      =link_to "#", class: "link__text" do
        = @product_s.category.name
    %li.link
      = icon("fa", "angle-right")
    %li.link
      =link_to "#", class: "link__text" do
        = @product_s.product_name
  
.main-contents
  .main__show
    .contents
      .contents__text
        %h2.image-name
          = @product_s.product_name
      .contents__image
        = image_tag @product_s.images.first.image.url, class: "beef-image"
        .contents__image__small
          - @product_s.images.each do |image|
            = image_tag image.image.url
        .contents__price
          %span.price
            ¥
            = @product_s.price
        .contents__tax
          %span.tax
            (税込)送料込み
      .detail
        = @product_s.product_detail
      - if @product.user == current_user || !user_signed_in?
      - else
        .contents__sellBtn
          = link_to purchase_check_product_path(@product), class: "purchaseBtn", method: :get do
            .link__sellBtn__text
              購入画面に進む
      .contents__table
        %table.main-table
          %tr.table
            %th.left-table 出品者
            %th.right-table 
              = @product_s.user.nickname
          %tr.table
            %th.left-table カテゴリー
            %th.right-table
              %ul
                %li
                  = @product_s.category.root.name
                %li
                  = @product_s.category.parent.name
                %li
                  = @product_s.category.name
          %tr.table
            %th.left-table ブランド
            %th.right-table
              = @product_s.brand
          %tr.table
            %th.left-table 商品のサイズ
            %th.right-table
              -if @product_s.delivery_time.id == 1 
                XXS以下
              -if @product_s.delivery_time.id == 2
                XS(SS)          
              -if @product_s.delivery_time.id == 3
                S
              -if @product_s.delivery_time.id == 4
                M
              -if @product_s.delivery_time.id == 5
                L            
              -if @product_s.delivery_time.id == 6
                XL(LL)
              -if @product_s.delivery_time.id == 7 
                2XL(3L)
              -if @product_s.delivery_time.id == 8
                3XL(4L)           
              -if @product_s.delivery_time.id == 9
                4XL(5L)
              -if @product_s.delivery_time.id == 10
                FREE SIZE
          %tr.table
            %th.left-table 商品の状態
            %th.right-table 
              -if @product_s.product_status.id == 1 
                新品、未使用
              -if @product_s.product_status.id == 2
                未使用に近い
              -if @product_s.product_status.id == 3
                目立った傷や汚れなし
              -if @product_s.product_status.id == 4
                やや傷や汚れあり
              -if @product_s.product_status.id == 5
                傷や汚れあり
              -if @product_s.product_status.id == 6
                全体的に状態が悪い
          %tr.table
            %th.left-table 配送料の負担
            %th.right-table 
              -if @product_s.delivery_fee.id == 1 
                送料込み (出品者負担)
              -if @product_s.delivery_fee.id == 2
                着払い (購入者負担)
          %tr.table
            %th.left-table 発送元の地域
            %th.right-table
              =link_to "#", class: "table-category" do
                = @product_s.delivery_area
          %tr.table
            %th.left-table 発送日の目安
            %th.right-table
              -if @product_s.delivery_fee.id == 1 
                1~2日で発送
              -if @product_s.delivery_fee.id == 2
                2~3日で発送            
              -if @product_s.delivery_fee.id == 3
                4~7日で発送
      .contents__option
        %ul.options
          %li.favorite
            = icon('fa', 'star')
            お気に入り 1
        %ul.options
          %li.report
            = icon('fa', 'flag')
            不適切な商品の通報
      .contents__relations
        .contents__relations--product
          .products
            =link_to "#", class: "relation" do
              レディースをもっと見る
            .relation-picture
              =link_to image_tag(src= "https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/7/a001.png", class: "curryrice"), "#"
              .image__text
                %h3.product-name
                  product1
                %ul.image-price
                  %li.price-test 10000円
                  %li
                    = icon('far', 'thumbs-up')
                  1
                %p.tax-include
                  (税込)
      - if @product.user == current_user
        .contents__delete
          = link_to 'この商品を削除する', product_path(@product), method: :delete, data: { confirm: 'この商品を削除してよろしいですか' }, class:"contents__delete--btn"
      -if @product.user == current_user
        .contents__edit
          = link_to "この商品を編集する", edit_product_path(@product.id), class: 'contents__edit--btn'
= render "items/app_banner"
= render "items/footer"
= render "items/display_btn"